pipeline {
    agent {
        docker {
            image "maven:3.6.2-jdk-8-slim"
            args "-v $HOME/.m2:/root/.m2"
        }
    }

    stages {
        stage( 'build' ) {
            steps {
                
                echo 'Building worker app'
                dir( 'worker' ) {
                    sh 'mvn compile'
                }        
            }
        }
        stage( 'test' ) {
            steps {
                echo 'Running Unit Test on worker app'
                dir( 'worker' ) {
                    sh 'mvn clean test'
                }
            }
        }
        stage( 'package' ) {
            steps {
                echo 'Packaging worker app'
                dir( 'worker' ) {
                    sh 'mvn package -DskipTests'
                }
                archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true 
            }
        }
    }

    post {
        always {
            echo 'the job is completed'
        }
    }
}