pipeline {
    agent any

    tools {
        maven 'maven 3.6.1'
    }

    stages {
        stage( 'one' ) {
            when {
                changeset "**/worker/**"
            }
            steps {
                
                echo 'Compiling worker app'
                dir( 'worker' ) {
                    sh 'mvn compile'
                }        
            }
        }
        stage( 'two' ) {
            when {
                changeset "**/worker/**"
            }
            steps {
                echo 'Running Unit Test on worker app'
                dir( 'worker' ) {
                    sh 'mvn clean test'
                }
            }
        }
        stage( 'three' ) {
            when {
                branch "master"
                changeset "**/worker/**"
            }
            steps {
                echo 'Packaging worker app'
                dir( 'worker' ) {
                    sh 'mvn package -DskipTests'
                }
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true 
            echo 'Building multibranch pipeline for worker is completed..'
        }
    }
}