pipeline {
    agent any

    tools {
        maven 'maven 3.6.1'
    }

    stages {
        stage( 'one' ) {
            steps {
                
                echo 'Compiling worker app'
                dir( 'worker' ) {
                    sh 'mvn compile'
                }        
            }
        }
        stage( 'two' ) {
            steps {
                echo 'Running Unit Test on worker app'
                dir( 'worker' ) {
                    sh 'mvn clean test'
                }
            }
        }
        stage( 'three' ) {
            steps {
                echo 'Packaging worker app'
                dir( 'worker' ) {
                    sh 'mvn package'
                }
            }
        }
    }

    post {
        always {
            echo 'Building multibranch pipeline for worker is completed..'
        }
    }
}